# Generated by Django 6.1 on 2026-08-17 13:32

import staff_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstaff',
            name='building',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='courses_taught',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='office_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=staff_admin.models.profile_image_path),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='rank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
