# Generated by Django 6.1 on 2026-08-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0002_academicstaff_building_academicstaff_courses_taught_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sarah Aliyu', max_length=200)),
                ('email', models.EmailField(default='admin@udus.edu.ng', max_length=254)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='admin_images/')),
            ],
        ),
    ]
