# Generated by Django 6.1 on 2026-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0003_systemadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstaff',
            name='working_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
