# Generated by Django 6.1 on 2026-09-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0004_alter_academicstaff_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicstaff',
            old_name='rank',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='academicstaff',
            name='unit',
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
