# Generated by Django 6.1 on 2026-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0005_rename_rank_academicstaff_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstaff',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
