# Generated by Django 6.1 on 2026-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0006_alter_academicstaff_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicstaff',
            old_name='research_interests',
            new_name='administrative_roles',
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
